### PR TITLE
Vendor all packages, not just top level packages

### PR DESCRIPTION
**Pull request by VoidingWarranties**
Build fails otherwise

### CODE REVIEW

**Comment by DavidVorick** [comment]
build fails otherwise?

**Comment by VoidingWarranties** [comment]
Yes, muxado merged their WIP branch which made some breaking changes, including getting rid of some of the sub packages.

**Comment by VoidingWarranties** [comment]
Our fork of muxado has a failing build, not just Sia.

**Comment by DavidVorick** [comment]
Can you investigate how seriously this changes the protocol? If we upgrade, will our new nodes still be able to talk to our old nodes?

**Comment by VoidingWarranties** [comment]
I do not know, but will investigate later.

**Comment by lukechampine** [comment]
I explored this many months ago, and the conclusion was that the protocols are incompatible. :/

I'm in favor of switching to muxado v2, but we should evaluate our other options. I'm not sure how bad the compatibility code would be, but I'm actually somewhat optimistic. In my head, it looks like this:

``` go
import (
    "github.com/inconshreveable/muxado"
    compatMuxado "github.com/NebulousLabs/muxado"
)

func (g *Gateway) Connect(addr modules.NetAddress) error {
    // dial
    conn, _ := net.DialTimeout("tcp", string(addr), dialTimeout)
    // read version
    var version string
    encoding.ReadObject(conn, &version, maxAddrLength)

    // construct peer with muxado session based on version
    var p peer
    if build.VersionCmp(version, "0.6.0") >= 0 {
        p.sess = muxado.Client(conn)
    } else {
        p.sess = compatMuxado.Client(conn)
    }
}
```

...and that should be it! Everything else is unaffected by the transport layer. As far as they know, they're just forming new connections and reading/writing.

(for the record, the compatibility code would look similar for other multiplexer packages, e.g. yamux)

**Pull request merged**
